[project]
name = "oxigenlib"
version = "0.1"
requires-python = "==3.12.*"

dependencies = [
  "pydantic== 2.11.4",
  "psygnal==0.12",
  "pyserial==3.5",
  "websockets==12.*",
]

[dependency-groups]
dev = ["sphinx", "sphinx_rtd_theme", "websockets", "pyinstaller"]
